### ISSUE TITLE
Getting error when I run npm run setup

### ISSUE THREAD

**Issue by Carter121** [guilhermebkel/uno-game#15]
This is the error:

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /var/www/html/abcdef/games/uno-game/node_modules/acorn-globals
npm ERR! dest /var/www/html/abcdef/games/uno-game/node_modules/.acorn-globals-gcIwcMnk
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/var/www/html/abcdef/games/uno-game/node_modules/acorn-globals' -> '/var/
www/html/abcdef/games/uno-game/node_modules/.acorn-globals-gcIwcMnk'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-03-17T15_28_30_992Z-debug.log
npm ERR! code 217
npm ERR! path /var/www/html/abcdef/games/uno-game
npm ERR! command failed
npm ERR! command sh -c npm install && npm run install:unapy && npm run install:unoenty && npm run bootstrap

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-03-17T15_28_31_119Z-debug.log
npm ERR! code 217
npm ERR! path /var/www/html/abcdef/games/uno-game
npm ERR! command failed
npm ERR! command sh -c npm run setup:app && npm run setup:env

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-03-17T15_28_31_230Z-debug.log

How do I fix it?

**Comment by guilhermebkel** [comment]
Hello @Carter121!

Can you tell me what is the node version you are currently using?

Besides, can you try running the **npm run setup** as **sudo** _(obviously it is not recommended to do that)_ to see if the problem persists.

**Comment by Carter121** [comment]
I'm using node version 15.12.0 and npm version 7.6.3.

When I run it with sudo I get this:
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /root/.npm/_cacache/index-v5/55/49/7a0c220c38e75dfed16c44317b4e3ec70e69ccf2c06c1a0ffa6909e6e490
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
npm ERR! code 243
npm ERR! path /var/www/html/abcdef/games/uno-game
npm ERR! command failed
npm ERR! command sh -c npm install && npm run install:unapy && npm run install:unoenty && npm run bootstrap
npm ERR! code 243
npm ERR! path /var/www/html/abcdef/games/uno-game
npm ERR! command failed
npm ERR! command sh -c npm run setup:app && npm run setup:env

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-24T15_25_21_967Z-debug.log

**Comment by guilhermebkel** [comment]
@Carter121 Got it :/ Can you try running it with node version 12.8?
