### ISSUE TITLE
[bug] Full card combo select bug

### ISSUE THREAD

**Issue by guilhermebkel** [guilhermebkel/uno-game#2]
In this game, the player is able to make card combo by clicking on them and grouping the ones with same type, but, the first card selected must respect the card on the top stack card (since the next play must respect the last one).

Being minded about that, we have the following problem:
- When selecting a full card combo and de-selecting de first combo card, the combo works even if the first card of the combo does not start with a valid type that matches the top stack card.

**Comment by ArcaneDiver** [comment]
Hey, could you assign me also this issue too because i have already resolved this issue😅.

**Comment by guilhermebkel** [comment]
@ArcaneDiver Hello! Thanks for solving this issue 😉, I'll assign you that.
