### ISSUE TITLE
Game looped in loading

### ISSUE THREAD

**Issue by SirLemons** [guilhermebkel/uno-game#27]
I have followed all of the installation steps correctly. I have ran the `setup` command and I have ran the dev:resources command to start up the redis server.

I have also run the dev build inside packages/unapy and packages/unoenty and it starts up the server. But once I put in a username it just is stuck on the animated UNO loading screen.
Fixes?

**Comment by guilhermebkel** [comment]
Hey @SirLemons! As you said you have done all the steps correctly, so it was expected to work 🤔

Can you take a screenshot of your **F12 - Network Tab** on the main page (the one which you put your username and got stuck)?
