### ISSUE TITLE
Error on `npm run setup`

### ISSUE THREAD

**Issue by GlowingUmbreon** [guilhermebkel/uno-game#28]
When trying to setup the project I get the following error:
```
lerna notice filter including "@uno-game/unapy"
lerna info filter [ '@uno-game/unapy' ]
lerna info Executing command in 1 package: "npm install"
@uno-game/unapy: npm WARN old lockfile 
@uno-game/unapy: npm WARN old lockfile The package-lock.json file was created with an old version of npm,
@uno-game/unapy: npm WARN old lockfile so supplemental metadata must be fetched from the registry.
@uno-game/unapy: npm WARN old lockfile 
@uno-game/unapy: npm WARN old lockfile This is a one-time fix-up, please be patient...
@uno-game/unapy: npm WARN old lockfile 
@uno-game/unapy: npm ERR! code E404
@uno-game/unapy: npm ERR! 404 Not Found - GET https://registry.npmjs.org/@uno-game%2fprotocols - Not found
@uno-game/unapy: npm ERR! 404 
@uno-game/unapy: npm ERR! 404  '@uno-game/protocols@*' is not in this registry.
@uno-game/unapy: npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
@uno-game/unapy: npm ERR! 404 
@uno-game/unapy: npm ERR! 404 Note that you can also install from a
@uno-game/unapy: npm ERR! 404 tarball, folder, http url, or git url.
@uno-game/unapy: npm ERR! A complete log of this run can be found in:
@uno-game/unapy: npm ERR!     /home/umbreon/.npm/_logs/2021-09-23T10_13_26_898Z-debug.log
lerna ERR! npm install exited 1 in '@uno-game/unapy'
[umbreon@umbreon-80xk uno-game]$
```

I've tried fixing it myself but I don't know enough about npm to be able to do so.

**Comment by guilhermebkel** [comment]
Hey @GlowingUmbreon! Sometime ago I noticed this bug when trying to use the app. It was caused because of the node version I was using to run the project. Can you tell me which Node version you are using to run the project and so, try to run it with **Node 14.17**?

In case it works, I'll try to add this information to the README in order to avoid it to happen again (or to package.json as well)

**Comment by GlowingUmbreon** [comment]
I'm using v16.10.0 (The current branch)
I will try with 14.17 in a bit.

**Comment by GlowingUmbreon** [comment]
Yep, npm run setup works fine on 14.17

**Comment by guilhermebkel** [comment]
Nice! I noticed that I added the engine config that specifies node version in the wrong place. Being minded about it, now it is at the correct file https://github.com/guilhermebkel/uno-game/commit/d51de7010e60dcf5f3c820cf806ba3dad5fb6cdb
