### ISSUE TITLE
[bug] Socket disconnection on mobile

### ISSUE THREAD

**Issue by guilhermebkel** [guilhermebkel/uno-game#4]
When players get into the **Table/Room Page** on mobile devices and minimizes the Browser, for some reason it causes a disconnection instantly on some devices.

So, being minded about that, we have two possible problems:
- When this disconnection happens, the disconnected player does not get a feedback about it.
- The disconnected player has to reload the page to connect to socket again, because there is no auto connection in case of disconnections.

**Comment by ArcaneDiver** [comment]
Hey, i would be glad to help you in this issue.
Now about the feedback an idea would be to use this component: [Snackbar](https://material-ui.com/components/snackbars/).
About the auto reconnection i think that by adding `autoConnect: true` would be a solution but i have to investigate more...

Then if you want to assign me this issue 🤗

**Comment by guilhermebkel** [comment]
Hello @ArcaneDiver!

I think the **Snackbar** is a good idea for giving feedback about the disconnection.

And about the `autoConnect: true`: I feel like I've tried something like that before but for some reason it did not work 🤔

I'll assign you to this issue, thanks! 😁

**Comment by ArcaneDiver** [comment]
Hey i implemented the feedback on disconnection, but i'm having some problem with the reproducing the disconnection on mobile devices. Because i tried on my mobile phone and it perfectly works.

**Comment by guilhermebkel** [comment]
@ArcaneDiver Got it! Being honest I did not find a pattern on this bug but I know that is the same thing as losing access to the internet after being connected to the socket on some room. So, to recreate it, you could do the following:

1. Access locally some room using your smartphone.
2. Disconnect your smartphone from Wi-fi or another network.

That way I think you're able to test it 🙂

Since I have two friends who came across this bug, after deploying this to production I can ask them for some testing. In case you want a log of this disconnection on production just call me that I add some **console.logs** on the production apps to give a look closer ✌🏻

**Comment by ArcaneDiver** [comment]
Hey👋, i have finally resolved this issue, now i'll refractor a bit my code, remove tons of console.log, ecc. and I tomorrow i'll make the PR.
Just a bit summary of how i resolved the issue.

There was 2 main problems. 
- The first problem was that when you reconnected the `SetPlayerData` event was not fired and then the server was not able to recognize the player. 
- The second problem was that the `pingTimeout` was too high and the server recognized when a player disconnected only when the player manually reconnected.

**Comment by guilhermebkel** [comment]
Hello @ArcaneDiver!

At first, thanks for caring about the code you write by doing a refactor on it 😁

Now, about the problems:

1. This really makes sense, since the **SetPlayerData** is a core event to keep the player on the application.
2. It does make sense as well, because when I set this value once, I thought a high value could be better but it is really bad when the player is disconnected from the game.

Thanks for helping to improve this game 😊
